name: Sync repository to mirrors

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  bitbucket:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to Bitbucket
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@bitbucket.org:the_archival_one/brs-psp-research-initiative.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"

  codeberg:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to Codeberg
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@codeberg.org:thearchivalone/BRS-PSP-Research-Initiative.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"

  beanstalk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to Beanstalk
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@the-archival-one.git.beanstalkapp.com:/the-archival-one/brs-psp-research-initiative.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"

  gitgud:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to GitGud
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@ssh.gitgud.io:thearchivalone/brs-psp-research-initiative.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"
 
  gitlab:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to GitLab
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'git@gitlab.com:thearchivalone1/BRS-PSP-Research-Initiative.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"
  
  sourceforge:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup secure connection
        id: secure
        run: |
          git pull origin main
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Sync up to Sourceforge
        id: sync
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://thearchivalone@git.code.sf.net/p/brs-psp-research-initiative-1/code'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
          GIT_SSH_NO_VERIFY_HOST: "true"

  archive:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compress Repository
        id: compress
        run:
          git archive --format=tar.gz -o Backup.tar.gz --prefix=$(basename $PWD)/ main
      - name: Sync up to Internet Archive
        id: ia_sync
        uses: qoijjj/internet-archive-upload@v7
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: BRS-Research-Initiative-Current
          files: Backup.tar.gz


