name: Sync repository to mirrors

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  bitbucket:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to Bitbucket
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          git remote add mirror git@bitbucket.org:the_archival_one/brs-psp-research-initiative.git
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'

  codeberg:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to Codeberg
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          git remote add mirror git@codeberg.org:thearchivalone/BRS-PSP-Research-Initiative.git
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
          
  gitgud:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to GitGud
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          git remote add mirror git@ssh.gitgud.io:thearchivalone/brs-psp-research-initiative.git
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
 
  gitlab:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to GitLab
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          git remote add mirror git@gitlab.com:thearchivalone1/BRS-PSP-Research-Initiative.git
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
  
  sourceforge:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to Sourceforge
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_PRIVATE }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KEY_PUBLIC }}" > ~/.ssh/id_ed25519.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          git remote add mirror ssh://thearchivalone@git.code.sf.net/p/brs-psp-research-initiative-1/code
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'

  roc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync up to Repo.or.cz
        id: sync
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ROC_SSH_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          echo "${{ secrets.ROC_SSH_PUBLIC }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          echo "${{ secrets.ROC_CERT }}" > ~/cert.pem
          git config --global http.https://repo.or.cz.sslCert "$HOME/cert.pem"
          git config --global http.https://repo.or.cz.sslKey "$HOME/.ssh/id_rsa"
          git remote add mirror https://repo.or.cz/BRS-PSP-Research-Initiative.git
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'

  archive:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compress Repository
        id: compress
        run:
          git archive --format=tar.gz -o Backup.tar.gz --prefix=$(basename $PWD)/ main
      - name: Sync up to Internet Archive
        id: ia_sync
        uses: qoijjj/internet-archive-upload@v7
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: BRS-Research-Initiative-Current
          files: Backup.tar.gz
